---
name: "Kitsu"
guid: "88d809e2-056b-47f4-9911-073949b9963f"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider
category: "Metadata"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.Kitsu.dll"
changelog: >
  changelog
