---
name: "Kitsu"
guid: "88d809e2-056b-47f4-9911-073949b9963f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kitsu.png"
version: "3"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider

category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Kitsu.dll"
changelog: |2-
  ### New features and improvements ###
  - chore: plugin images (#5) @h1dden-da3m0n

  ### Dependency updates ###
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#4) @dependabot

  ### CI & build changes ###
  - Update ci (#6) @h1dden-da3m0n
  - Let there be CI (#2) @oddstr13

  ### Code or Repo Maintenance ###
  - 10.8 support (#9) @crobibero

  ### Documentation updates ###
  - chore(doc): doc and editorconf update (#3) @h1dden-da3m0n
