---
name: "Kitsu"
guid: "88d809e2-056b-47f4-9911-073949b9963f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kitsu.png"
version: "2.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Kitsu.dll"
changelog: |
  - Split out from the Anime plugin
  - Remove dependency on DependencyInjection

